Repository DeveloperAcademy-POSTECH/MC3-Team9-Yetda, pull requests merged in 2022-07, with the labels that each got.

#3 :triangular_flag_on_post: Feat[#2] : CoreData 의 Entity를 만들고 구조를 완성했습니다.
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
  Yetda/Yetda/Present+CoreDataClass.swift
  Yetda/Yetda/Present+CoreDataProperties.swift
  Yetda/Yetda/Site+CoreDataClass.swift
  Yetda/Yetda/Site+CoreDataProperties.swift
  Yetda/Yetda/Yetda.xcdatamodeld/Yetda.xcdatamodel/contents
Labels: enhancement

#4 :hammer: Fix: main에 머지해버렸네요. main을 다시 Develop에 머지
  README.md
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
  Yetda/Yetda/Present+CoreDataClass.swift
  Yetda/Yetda/Present+CoreDataProperties.swift
  Yetda/Yetda/Site+CoreDataClass.swift
  Yetda/Yetda/Site+CoreDataProperties.swift
  Yetda/Yetda/Yetda.xcdatamodeld/Yetda.xcdatamodel/contents
Labels: wontfix

#12 :sparkles: Feat[#10] : ChrdShareCompletionViewController 구현
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/Contents.json
  Yetda/Yetda/Assets.xcassets/background.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/background.imageset/background.png
  Yetda/Yetda/DidCardShare.storyboard
  Yetda/Yetda/DidCardShareViewController.swift
  Yetda/Yetda/DidPresent.storyboard
  Yetda/Yetda/DidPresentViewController.swift
  Yetda/Yetda/SceneDelegate.swift
Labels: enhancement

#19 ✨Feat[#6]: CardCollectionView를 띄우는 데에 필요한 MVVM 구조 완성
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/View/CardCell.swift
  Yetda/Yetda/View/CardListView.swift
  Yetda/Yetda/ViewController/HomeViewController.swift
  Yetda/Yetda/ViewModel/CardListViewModel.swift
Labels: enhancement

#21 💄 Design : UI 수정, 이미지 파일 교체
  Yetda/Yetda/Assets.xcassets/background.imageset/background.png
  Yetda/Yetda/DidPresent.storyboard
Labels: Design

#23 ✨ Feat : MakeCardDescription 뷰를 구현 중
  .DS_Store
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/Assets.xcassets/photo1.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/photo1.imageset/photo1.jpeg
  Yetda/Yetda/Assets.xcassets/photo2.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/photo2.imageset/photo2.jpeg
  Yetda/Yetda/Assets.xcassets/photo3.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/photo3.imageset/photo3.jpeg
  Yetda/Yetda/Assets.xcassets/photo4.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/photo4.imageset/photo4.jpeg
  Yetda/Yetda/Assets.xcassets/photo5.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/photo5.imageset/photo5.jpeg
  Yetda/Yetda/Base.lproj/LaunchScreen.storyboard
  Yetda/Yetda/Base.lproj/Main.storyboard
  Yetda/Yetda/KeywordCollectionCell.swift
  Yetda/Yetda/MakeCard.storyboard
  Yetda/Yetda/MakeCardDescriptionView.swift
  Yetda/Yetda/PhotoCollectionCell.swift
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/ViewController.swift
Labels: enhancement

#27 ✨Feat: Site collection view 를 만들었습니다
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/Assets.xcassets/BackgroundDesign.imageset/BackgroundDesign.pdf
  Yetda/Yetda/Assets.xcassets/BackgroundDesign.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/ShadowCell.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/ShadowCell.imageset/ShadowCell.pdf
  Yetda/Yetda/Assets.xcassets/sitePlaceIcon.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/sitePlaceIcon.imageset/sitePlaceIcon.pdf
  Yetda/Yetda/Assets.xcassets/siteViewButton.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/siteViewButton.imageset/siteViewButton.pdf
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/SiteCell.swift
  Yetda/Yetda/SiteCollectionView.storyboard
  Yetda/Yetda/SiteModel.swift
  Yetda/Yetda/SiteViewController.swift
Labels: enhancement

#29 :ambulance: Revert : 파일이 깨져어서 다시 돌립니다.
  Yetda/Yetda.xcodeproj/xcuserdata/parkgeunil.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: bug

#36 Make card description/navigation
  .DS_Store
  Yetda/.DS_Store
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/AppDelegate.swift
  Yetda/Yetda/KeywordCollectionCell.swift
  Yetda/Yetda/MakeCard.storyboard
  Yetda/Yetda/MakeCardDescriptionView.swift
  Yetda/Yetda/MakeCardDescriptionViewController.swift
  Yetda/Yetda/MakeCardStoryViewController.swift
  Yetda/Yetda/PhotoCollectionCell.swift
  Yetda/Yetda/SceneDelegate.swift
Labels: enhancement

#35 ✨ Feat: ShareKaKao 버튼 구성
  .gitignore
  Yetda/Podfile
  Yetda/Podfile.lock
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda.xcworkspace/contents.xcworkspacedata
  Yetda/Yetda.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Yetda/Yetda.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Yetda/Yetda/AbleShareKaKao.swift
  Yetda/Yetda/DidCardShareViewController.swift
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/ShareButton+Extension.swift
Labels: enhancement

#39 :sparkles: Feat[#17] Add CardDetailViewController
  Yetda/.DS_Store
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/CardDetailView.swift
  Yetda/Yetda/CardDetailViewController.swift
  Yetda/Yetda/ContentsCell.swift
  Yetda/Yetda/DummyData.swift
  Yetda/Yetda/HeaderView.swift
  Yetda/Yetda/KeywordCell.swift
  Yetda/Yetda/MapCell.swift
Labels: enhancement

#44 ✨ Feat[#43]: 이동 애니메이션 확장/접기 로 만들었습니다
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Yetda/Yetda/Assets.xcassets/custom.airplane.arrival.imageset/Contents.json
  Yetda/Yetda/Assets.xcassets/custom.airplane.arrival.imageset/custom.airplane.arrival@2x.png
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/Site/SiteCell.swift
  Yetda/Yetda/Site/SiteCollectionView.storyboard
  Yetda/Yetda/Site/SiteViewController.swift
Labels: enhancement

#45 ✨Feat: Site search bar 2
  Yetda/Yetda/Assets.xcassets/YettdaMainBackground.colorset/Contents.json
  Yetda/Yetda/Assets.xcassets/YettdaMainBlue.colorset/Contents.json
  Yetda/Yetda/Assets.xcassets/YettdaMainGray.colorset/Contents.json
  Yetda/Yetda/Assets.xcassets/YettdaMainLightBlue.colorset/Contents.json
  Yetda/Yetda/Site/SiteCollectionView.storyboard
  Yetda/Yetda/Site/SiteViewController.swift
Labels: enhancement

#48 ✨ Feat : appDelegate에 저장하지 않기 위해 keyword 로직 다시 짰습니다.
  .DS_Store
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/AppDelegate.swift
  Yetda/Yetda/MakeCard/KeywordCollectionCell.swift
  Yetda/Yetda/MakeCard/MakeCard.storyboard
  Yetda/Yetda/MakeCard/MakeCardDescriptionViewController.swift
  Yetda/Yetda/MakeCard/MakeCardStoryViewController.swift
  Yetda/Yetda/SceneDelegate.swift
Labels: enhancement

#49 ✨ Feat : Firebase DB를 연결했습니다.
  Yetda/Podfile
  Yetda/Podfile.lock
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda.xcodeproj/xcuserdata/parkgeunil.xcuserdatad/xcschemes/xcschememanagement.plist
  Yetda/Yetda/AppDelegate.swift
  Yetda/Yetda/Base.lproj/Main.storyboard
  Yetda/Yetda/Home/CardListViewModel.swift
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/Model/Present+CoreDataClass.swift
  Yetda/Yetda/Model/Present+CoreDataProperties.swift
  Yetda/Yetda/Model/Present.swift
  Yetda/Yetda/Model/Site+CoreDataClass.swift
  Yetda/Yetda/Model/Site+CoreDataProperties.swift
  Yetda/Yetda/ViewController.swift
  Yetda/Yetda/Yetda.xcdatamodeld/.xccurrentversion
Labels: enhancement

#52 ✨Feat[#50]: My page view 구현
  .DS_Store
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Yetda/Yetda/MyPage/MyPageView.storyboard
  Yetda/Yetda/MyPage/MyPageViewController.swift
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/Site/SiteCollectionView.storyboard
  Yetda/Yetda/Site/SiteViewController.swift
Labels: enhancement

#56 ✨ Feat[#47]: 카드 삭제 기능을 구현했습니다
  Yetda/Podfile.lock
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/Home/CardCell.swift
  Yetda/Yetda/Home/CardListViewModel.swift
  Yetda/Yetda/Home/HomeViewController.swift
Labels: enhancement

#55 :sparkles: Feat[#17]: CardDetailViewController 기능 추가
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/CardDetail/CardDetailView.swift
  Yetda/Yetda/CardDetail/CardDetailViewController.swift
  Yetda/Yetda/CardDetail/ContentsCell.swift
  Yetda/Yetda/CardDetail/KeywordCell.swift
  Yetda/Yetda/CardDetail/MapCell.swift
  Yetda/Yetda/Info.plist
Labels: enhancement

#59 ✨Feat: Firebase 데이터 저장 로직을 었습니다.
  .DS_Store
  Yetda/Podfile
  Yetda/Podfile.lock
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda.xcodeproj/xcuserdata/parkgeunil.xcuserdatad/xcschemes/xcschememanagement.plist
  Yetda/Yetda/AppDelegate.swift
  Yetda/Yetda/FirebaseFirestoreManager.swift
  Yetda/Yetda/FirebaseStorageManager.swift
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MakeCard/MakeCard.storyboard
  Yetda/Yetda/MakeCard/MakeCardDescriptionViewController.swift
  Yetda/Yetda/Model/Present.swift
  Yetda/Yetda/ViewController.swift
Labels: enhancement

#61 ✨Feat: [#53] , [#54]
  Yetda/Podfile.lock
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/OnBoarding/OnBoardingSecondStepController.swift
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/Search/SearchResultViewController.swift
  Yetda/Yetda/Search/SearchSiteCell.swift
  Yetda/Yetda/Search/SearchSiteModel.swift
  Yetda/Yetda/Search/SearchViewModel.swift
  Yetda/Yetda/UserSiteModel.swift
  Yetda/Yetda/ko.lproj/LocalizingFile.strings
Labels: enhancement

#63 ✨ Feat[#62]: HomeVC에 온보딩 추가하고 다른 뷰로 이동 연결
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MakeCard/MakeCard.storyboard
  Yetda/Yetda/SceneDelegate.swift
Labels: enhancement

#64 Feat: My page view Modality
  .DS_Store
  Yetda/Yetda/MyPage/MyPageView.storyboard
  Yetda/Yetda/MyPage/MyPageViewController.swift
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/Site/SiteCollectionView.storyboard
  Yetda/Yetda/Site/SiteViewController.swift
Labels: enhancement

#67 🎨 : 디자인 변경, 유저 디폴트 적용
  Yetda/Yetda/OnBoarding/OnBoardingFirstStepController.swift
  Yetda/Yetda/OnBoarding/OnBoardingSecondStepController.swift
  Yetda/Yetda/OnBoarding/OnBoardingViewController.swift
  Yetda/Yetda/Search/SearchResultViewController.swift
Labels: enhancement, Design

#68 :sparkles: Feat[#17] Card detail view controller share기능 추가
  Yetda/Yetda/CardDetail/CardDetailViewController.swift
Labels: enhancement

#73 ✨ Feat[#65]: 텍스트필드에서 요구되는 조건 사항을 변경했습니다.
  .DS_Store
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/Assets.xcassets/YettdaSubDisabledButton.colorset/Contents.json
  Yetda/Yetda/Info.plist
  Yetda/Yetda/MakeCard/KeywordCollectionCell.swift
  Yetda/Yetda/MakeCard/MakeCard.storyboard
  Yetda/Yetda/MakeCard/MakeCardDescriptionViewController.swift
  Yetda/Yetda/MakeCard/MakeCardStoryViewController.swift
Labels: enhancement

#74 ✨Feat[#70]: 유저의 여행지를 저장하고 UI 업데이트 하는 로직 구현
  Yetda/Podfile.lock
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MyPage/MyPageView.storyboard
  Yetda/Yetda/MyPage/MyPageViewController.swift
  Yetda/Yetda/OnBoarding/OnBoardingSecondStepController.swift
  Yetda/Yetda/OnBoarding/OnBoardingViewController.swift
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/Search/SearchResultViewController.swift
  Yetda/Yetda/Site/SiteCell.swift
  Yetda/Yetda/Site/SiteModel.swift
  Yetda/Yetda/Site/SiteViewController.swift
  Yetda/Yetda/UserSiteModel.swift
Labels: enhancement

#76 ✨Feat[#75] : 데이터 저장로직을 만들었습니다.
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda.xcodeproj/xcuserdata/parkgeunil.xcuserdatad/xcschemes/xcschememanagement.plist
  Yetda/Yetda/FirestoreManager.swift
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MakeCard/MakeCardDescriptionViewController.swift
  Yetda/Yetda/MakeCard/MakeCardStoryViewController.swift
  Yetda/Yetda/Model/Present.swift
  Yetda/Yetda/Search/SearchResultViewController.swift
  Yetda/Yetda/StorageManager.swift
Labels: enhancement
