Repository DeveloperAcademy-POSTECH/MC3-Team9-Yetda, pull requests merged in 2022-08, with the labels that each got.

#79 ✨Feat[#77] : 카드 작성 후 데이터 넘길 준비하고 넘겨진 것을 확인했습니다.
  .DS_Store
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MakeCard/MakeCard.storyboard
  Yetda/Yetda/MakeCard/MakeCardDescriptionViewController.swift
  Yetda/Yetda/MakeCard/MakeCardStoryViewController.swift
Labels: enhancement

#80 🎨 : 검색 결과 백그라운드뷰 수정, 온보딩 present 형태로 변경
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/Search/SearchResultViewController.swift
  Yetda/Yetda/Site/SiteViewController.swift
Labels: enhancement, Design

#81 ✨Feat : 로그아웃, 회원탈퇴 기능을 만들었습니다.
  Yetda/Yetda/MyPage/MyPageViewController.swift
Labels: enhancement

#82 :art: Design[#17] CardDetailView 백그라운드 색상 수정 및 이미지 뷰 수정
  Yetda/Yetda/CardDetail/CardDetailViewController.swift
  Yetda/Yetda/CardDetail/ContentsCell.swift
  Yetda/Yetda/CardDetail/HeaderView.swift
Labels: Design

#84 💄 Design: 온보딩, 검색결과 뷰의 UI 수정
  Yetda/Yetda/OnBoarding/OnBoardingFirstStepController.swift
  Yetda/Yetda/OnBoarding/OnBoardingSecondStepController.swift
  Yetda/Yetda/Search/SearchResultViewController.swift
Labels: Design

#86 🐛Fix: 누락된 기능들을 복구했습니다
  .DS_Store
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/CardDetail/CardDetailViewController.swift
  Yetda/Yetda/GoogleService-Info.plist
  Yetda/Yetda/Home/CardCell.swift
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MakeCard/MakeCardStoryViewController.swift
  Yetda/Yetda/OnBoarding/OnBoardingViewController.swift
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/StorageManager.swift
Labels: bug

#89 ✨ Feat: 카카오 공유 및 연관된 뷰 연결
  Yetda/Podfile.lock
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/AppDelegate.swift
  Yetda/Yetda/CardDetail/CardDetailViewController.swift
  Yetda/Yetda/CardDetail/DummyData.swift
  Yetda/Yetda/CardDetail/HeaderView.swift
  Yetda/Yetda/CardDetail/KeywordCell.swift
  Yetda/Yetda/Info.plist
  Yetda/Yetda/SceneDelegate.swift
  Yetda/Yetda/Sharing/AbleShareKaKao.swift
  Yetda/Yetda/StorageManager.swift
Labels: enhancement

#91 ⚒️ Fix : Login 플로우가 바뀌어서 수정했습니다.
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MyPage/MyPageViewController.swift
  Yetda/Yetda/OnBoarding/OnBoardingFirstStepController.swift
Labels: enhancement

#92 ✨ Feat : URL 파싱, 딜리게이트 설정
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/OnBoarding/OnBoardingViewController.swift
  Yetda/Yetda/SceneDelegate.swift
Labels: enhancement

#93 Chore : Mypage, HomeView 수정
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MakeCard/MakeCardStoryViewController.swift
  Yetda/Yetda/MyPage/MyPageViewController.swift
  Yetda/Yetda/Sharing/AbleShareKaKao.swift
Labels: bug, enhancement

#94 ⚒️ Fix: 로고를 넣고, 카드 디테일 정보를 수정하고, 이미지 받아오는 로직을 수정했습니다.
  .DS_Store
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/120-1.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/120.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/180.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/29.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/40-1.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/40-2.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/40.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/58-1.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/58.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/60.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/80-1.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/80.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/87.png
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/Contents.json
  Yetda/Yetda/Assets.xcassets/AppIcon.appiconset/appstore.png
  Yetda/Yetda/CardDetail/CardDetailViewController.swift
  Yetda/Yetda/Home/CardCell.swift
  Yetda/Yetda/Home/HomeViewController.swift
  Yetda/Yetda/MakeCard/MakeCard.storyboard
  Yetda/Yetda/MakeCard/MakeCardDescriptionViewController.swift
  Yetda/Yetda/MakeCard/MakeCardStoryViewController.swift
Labels: enhancement

#96 :sparkles: Feat: 카카오 API_Key 숨김, CardDetailView 기능 추가
  Yetda/Yetda.xcodeproj/project.pbxproj
  Yetda/Yetda/AppDelegate.swift
  Yetda/Yetda/Assets.xcassets/YettdaMainYellow.colorset/Contents.json
  Yetda/Yetda/CardDetail/CardDetailViewController.swift
  Yetda/Yetda/CardDetail/HeaderView.swift
  Yetda/Yetda/CardDetail/MapCell.swift
Labels: enhancement, Design
